#!/usr/bin/python
import sys
import socket

ADDR = "127.0.0.1"
PORT = int(sys.argv[1])

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((ADDR, PORT))

while True:
    data, addr = sock.recvfrom(1500)
    print "received message:", data

